### ISSUE TITLE
Script reconnect fails after unstable DNS resolution

### ISSUE THREAD

**Issue by mt-mrx** [mpepping/solarman-mqtt#39]
Hi,

I upgraded yesterday to v0.6.2 (docker container). I don't think the issue is related to that upgrade but to an unstable ISP internet connection I had during the night. My monitoring shows me that I had a lot of paket loss on my ISP uplink during the night, that probably caused the DNS resolution to fail at "02:45:40". It looks like the script couldn't really recover from that because after the "07:58:54" message I see no further tries to fetch data until I finally restarted the docker container shortly before "15:30:48"
The only modification I did to the code was to change the default query interval from 300 to 270 seconds. (Btw. it would be nice to have an environment variable which you could set in your docker-compose file to pass that parameter to the script inside the docker container)

See the following logs (I condensed all the identical repeating messages by using ...):
```
INFO:root:Starting daemonized with a 270 seconds run interval
INFO:root:2022-10-10 14:20:44 - Inverter DeviceState: 1 -> Publishing to MQTT ...
...
INFO:root:2022-10-10 18:53:20 - Inverter DeviceState: 1 -> Publishing to MQTT ...
INFO:root:2022-10-10 18:57:52 - Inverter DeviceState: 3-> Only status MQTT publish (probably offline due to nighttime shutdown)
...
INFO:root:2022-10-11 02:45:40 - Inverter DeviceState: 3-> Only status MQTT publish (probably offline due to nighttime shutdown)
ERROR:root:Unable to fetch token: [Errno -3] Temporary failure in name resolution
INFO:root:Starting daemonized with a 270 seconds run interval
INFO:root:2022-10-11 02:50:35 - Inverter DeviceState: 3-> Only status MQTT publish (probably offline due to nighttime shutdown)
...
INFO:root:2022-10-11 04:30:38 - Inverter DeviceState: 3-> Only status MQTT publish (probably offline due to nighttime shutdown)
ERROR:root:Unable to fetch token: [Errno -3] Temporary failure in name resolution
INFO:root:Starting daemonized with a 270 seconds run interval
ERROR:root:Unable to fetch token: [Errno 104] Connection reset by peer
INFO:root:Starting daemonized with a 270 seconds run interval
INFO:root:2022-10-11 04:36:58 - Inverter DeviceState: 3-> Only status MQTT publish (probably offline due to nighttime shutdown)
...
INFO:root:2022-10-11 07:38:12 - Inverter DeviceState: 3-> Only status MQTT publish (probably offline due to nighttime shutdown)
ERROR:root:Unable to fetch token: [Errno 104] Connection reset by peer
INFO:root:Starting daemonized with a 270 seconds run interval
INFO:root:2022-10-11 07:44:53 - Inverter DeviceState: 3-> Only status MQTT publish (probably offline due to nighttime shutdown)
INFO:root:2022-10-11 07:49:25 - Inverter DeviceState: 3-> Only status MQTT publish (probably offline due to nighttime shutdown)
INFO:root:2022-10-11 07:53:57 - Inverter DeviceState: 3-> Only status MQTT publish (probably offline due to nighttime shutdown)
INFO:root:2022-10-11 07:58:54 - Inverter DeviceState: 3-> Only status MQTT publish (probably offline due to nighttime shutdown)
ERROR:root:Unable to fetch token: Remote end closed connection without response
INFO:root:Starting daemonized with a 270 seconds run interval
INFO:root:Starting daemonized with a 270 seconds run interval
INFO:root:2022-10-11 15:30:48 - Inverter DeviceState: 1 -> Publishing to MQTT ...
```

**Comment by mpepping** [comment]
Thanks for the detailed description and logging, @mt-mrx! I'm not able to reproduce the 'hanging' connection .. but I think the cause is in the fact that, by default, the request library has an infinite timeout duration for requests. I've added a default timeout to these requests now. So, that being the likely cause, this should resolve the issue. 

It's in [v0.7.2](https://github.com/mpepping/solarman-mqtt/pkgs/container/solarman-mqtt), if you want to give it a go.  

Regarding your comment on configuring the interval. Passing a custom interval via docker-compose is possible. Not via an environment var, but by adding a command param like `command: -d -i 270` in your docker-compose.yml file. Looking at the docker-compose example in the [README.md](https://github.com/mpepping/solarman-mqtt/blob/main/README.md), adding the `command` parameter would make it look something like:

```yaml
version: '3'

services:
  solarman-mqtt:
    image: ghcr.io/mpepping/solarman-mqtt:latest
    command: -d -i 270
    container_name: "solarman-mqtt"
    environment:
    - TZ=Europe/Amsterdam
    volumes:
      - /opt/solarman-mqtt/config.json:/opt/app-root/src/config.json
    restart: unless-stopped
```

Again, thanks for the feedback and improvement!
