### ISSUE TITLE
Feature: Setting Inverter Limit

### ISSUE THREAD

**Issue by tobit6795** [mpepping/solarman-mqtt#87]
It is now possible to set inverter limit by percentage via UI. It would be great if this would be added to this add on as it would help to implement zero feed .

**Comment by mpepping** [comment]
Sounds cool. Do you have link to Home Assistant documentation or release notes that describe this? Couldn't find anything describing this.

**Comment by tobit6795** [comment]
Hi. 
The closest i could find is this open issue:
https://github.com/tbnobody/OpenDTU/issues/815

There are already some implementations by users:

https://github.com/reinhard-brandstaedter/solarflow/blob/master/solarflow-control/solarflow-control.py
or
https://github.com/z-master42/solarflow/blob/main/script_nur_nulleinspeisung.yaml

I hope that helps.

I imagine something like a input number, based on inverter with given min and max values, that can be set for example to 600 for an 800w inverter

**Comment by mpepping** [comment]
As I understand zero feed-in, requires two things: get the current power limit from the inverter, and set the current power limit on the inverter. Since solarman-mqtt only retrieves data from the inverter installation, only getting the power limit value would be possible.

My own installation does not provide any data related to the current power limit. I think it's too outdated :). If anyone can provide the data from their installation (using `"debug": true` in the config file), then we would be able to publish the current power limit data to MQTT. I'll close this issue for now; feel free to comment with any example data to reopen this issue.
